name = "MultiGridBarrierPETSc"
uuid = "25e6f22c-346c-4a8d-b463-5e1d66a49b87"
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MultiGridBarrier = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SafePETSc = "50acdc01-ce88-4ca7-bd87-6916c254362e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Documenter = "1.16.0"
MPI = "0.20.23"
MultiGridBarrier = "0.11.28"
SafePETSc = "0.1.12"
julia = "1.10"
