name = "MultiGridBarrierPETSc"
uuid = "25e6f22c-346c-4a8d-b463-5e1d66a49b87"
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MultiGridBarrier = "9e2c1f1d-9131-4ad4-b32f-bd2a0b0ecd1e"
SafePETSc = "50acdc01-ce88-4ca7-bd87-6916c254362e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MPI = "0.20.23"
MultiGridBarrier = "0.11.28"
SafePETSc = "0.1.12"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
